### ISSUE TITLE
关于motivation的一些疑问

### ISSUE THREAD

**Issue by yinghuozijin** [chuangchuangtan/C2P-CLIP-DeepfakeDetection#2]
看了您的论文后，感觉好像真正起作用的就是LoRA，似乎跟您文中所写的motivation没啥关系。
对CLIP提取到的图像特征进行变换后，再使用CllipCap显然会得到不同的文本内容，因此我认为您在文中得到的结论：**CLIP通过识别相似的概念从而实现检测** 是不成立的，不知道您有什么不同的看法？

**Comment by chuangchuangtan** [comment]
1. Lora 和 概念注入同时起作用达到论文中效果，结果参考 [Ablation Study](https://github.com/chuangchuangtan/C2P-CLIP-DeepfakeDetection#ablation-study).
2. 变换后的图像CLIP特征 包含有更多的伪造信息，通过对这个伪造信息进行分析，探究CLIP伪造检测机理是非常有意义的。
3. **利用CllipCap解码变换后特征显然会得到不同的文本内容** 是没错的。如何分析这些文本内容，得出结论，并通过实验验证结论是本文的一个重要贡献。

**Comment by yinghuozijin** [comment]
我觉得**概念注入+对比学习**其实起到的就是给Real和Fake两类分配一个anchor（类别中心）的作用，虽然不知道使用anchor是否能达到相同的效果，不知道我这样理解的是否有问题？

**Comment by chuangchuangtan** [comment]
可以这么理解，这个 类别中心 是对比学习特征空间里的，是一种隐式center
